list: $/gibraltarsf/pmo/models/risktype/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Risktype
title: Tipos de riesgo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/risktypes/update/:id'
