list: $/gibraltarsf/pmo/models/valcriteria/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Valcriteria
title: Valcriterias
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/valcriterias/update/:id'
