list: $/gibraltarsf/pmo/models/nivel/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Nivel
title: Niveles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/niveles/update/:id'
