list: $/gibraltarsf/pmo/models/esfcriteria/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Esfcriteria
title: Esfcriterias
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/esfcriterias/update/:id'
