list: $/gibraltarsf/pmo/models/riscriteria/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Riscriteria
title: Riscriterias
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/riscriterias/update/:id'
