list: $/gibraltarsf/pmo/models/mejora/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Mejora
title: Mejoras
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/mejoras/update/:id'
