list: $/gibraltarsf/pmo/models/idea/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Idea
title: Ideas
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/ideas/update/:id'
filter: $/gibraltarsf/pmo/controllers/ideas/config_filter.yaml