# ===================================
#  Relation Behavior Config
# ===================================


valueweights:
    label: Criterios de valoración
    readOnly: true
    view:
        list: ~/plugins/gibraltarsf/pmo/models/valcriteria/columns_idea.yaml
        form: ~/plugins/gibraltarsf/pmo/models/valcriteria/fields_idea.yaml
        showSearch: false
        toolbarButtons:
        defaultSort:
            column: name
            direction: asc
        recordsPerPage: 15
        readOnly: true
        showSetup: false

#    pivot:
#        form: ~/plugins/gibraltarsf/importaciones/models/period/periodSupplierFields.yaml
riskweights:
    label: Criterios de riesgo
    readOnly: true
    view:
        list: ~/plugins/gibraltarsf/pmo/models/riscriteria/columns_idea.yaml
        form: ~/plugins/gibraltarsf/pmo/models/riscriteria/fields_idea.yaml
        showSearch: false
        toolbarButtons: 
        defaultSort:
            column: name
            direction: asc
        recordsPerPage: 15
        readOnly: false
        showSetup: false
