# ===================================
#  Relation Behavior Config
# ===================================


valueweights:
    label: Criterios de valoración
    readOnly: true

    view:
        list: ~/plugins/gibraltarsf/pmo/models/valcriteria/columns_idea.yaml
        form: ~/plugins/gibraltarsf/pmo/models/valcriteria/fields_idea.yaml
        showSearch: false
        #toolbarButtons:
        defaultSort:
            column: name
            direction: asc
        recordsPerPage: 15
        readOnly: true
        showSetup: false

#    pivot:
#        form: ~/plugins/gibraltarsf/importaciones/models/period/periodSupplierFields.yaml
esfuerzoweights:
    label: Criterios de esfuerzo
    readOnly: true

    view:
        list: ~/plugins/gibraltarsf/pmo/models/esfcriteria/columns_idea.yaml
        form: ~/plugins/gibraltarsf/pmo/models/esfcriteria/fields_idea.yaml
        showSearch: false
        #toolbarButtons:
        defaultSort:
            column: name
            direction: asc
        recordsPerPage: 15
        readOnly: true
        showSetup: false


riskweights:
    label: Criterios de riesgo
    readOnly: true
    view:
        list: ~/plugins/gibraltarsf/pmo/models/riscriteria/columns_idea.yaml
        form: ~/plugins/gibraltarsf/pmo/models/riscriteria/fields_idea.yaml
        showSearch: false
        toolbarButtons: 
        defaultSort:
            column: name
            direction: asc
        recordsPerPage: 15
        readOnly: false
        showSetup: false

riesgos:
    label: Riesgos
    readOnly: false
    view:
        list: ~/plugins/gibraltarsf/pmo/models/riesgo/columns.yaml
        form: ~/plugins/gibraltarsf/pmo/models/riesgo/fields.yaml
        showSearch: true
        toolbarButtons:   create | delete
        defaultSort:
            column: name
            direction: asc
        recordsPerPage: 15
        #scope: isEnabled
    manage:
        title: Riesgos disponibles
        #form: ~/plugins/gibraltarsf/importaciones/models/period/fields.yaml
        form: ~/plugins/gibraltarsf/pmo/models/riesgo/fields.yaml
        list: ~/plugins/gibraltarsf/pmo/models/riesgo/columns.yaml
        showSearch: true
        #scope: isEnabled
    #pivot:
    #    form: ~/plugins/gibraltarsf/pmo/models/riesgo/fields_pivot.yaml


etapas:
    label: Tareas resumen - Hitos
    readOnly: false
    view:
        list: ~/plugins/gibraltarsf/pmo/models/etapa/columns_nested.yaml
        form: ~/plugins/gibraltarsf/pmo/models/etapa/fields_nested.yaml
        showSearch: true
        toolbarButtons:   create 
        defaultSort:
            column: inicio
            direction: asc
        recordsPerPage: 15
        showTree: true
        #scope: isEnabled
    manage:
        title: Tareas resumen - Hitos
        #form: ~/plugins/gibraltarsf/importaciones/models/period/fields.yaml
        form: ~/plugins/gibraltarsf/pmo/models/etapa/fields_nested.yaml
        list: ~/plugins/gibraltarsf/pmo/models/etapa/columns_nested.yaml
        showSearch: true
        
        #scope: isEnabled
    #pivot:
    #    form: ~/plugins/gibraltarsf/pmo/models/riesgo/fields_pivot.yaml


novedades:
    label: Novedades
    readOnly: false
    view:
        list: ~/plugins/gibraltarsf/pmo/models/novedad/columns.yaml
        form: ~/plugins/gibraltarsf/pmo/models/novedad/fields.yaml
        showSearch: true
        toolbarButtons:   create | delete
        defaultSort:
            column: fecha
            direction: asc
        recordsPerPage: 15
        #scope: isEnabled
    manage:
        title: Novedad
        #form: ~/plugins/gibraltarsf/importaciones/models/period/fields.yaml
        form: ~/plugins/gibraltarsf/pmo/models/novedad/fields.yaml
        list: ~/plugins/gibraltarsf/pmo/models/novedad/columns.yaml
        showSearch: true
        #scope: isEnabled
    #pivot:
    #    form: ~/plugins/gibraltarsf/pmo/models/riesgo/fields_pivot.yaml