list: $/gibraltarsf/pmo/models/score/columns.yaml
modelClass: Gibraltarsf\Pmo\Models\Score
title: Scores
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gibraltarsf/pmo/scores/update/:id'
